env:
  contexts:
    - name: "JuiceShopContext"
      urls:
        - "http://localhost:3000"
  parameters:
    failOnError: false
    failOnWarning: false

jobs:
  - type: spider
    parameters:
      context: "JuiceShopContext"
      maxDuration: 2

  - type: activeScan
    parameters:
      context: "JuiceShopContext"

  - type: report
    parameters:
      template: "traditional-html"
      reportFile: "zap_report.html"
      reportTitle: "ZAP Scan Report"
