rules:
  - id: detect-insecure-sql-alt
    pattern: db.query($SQL + $VAR)
    message: "¡ALERTA! Se detectó una consulta SQL construida mediante concatenación."
    languages: [javascript]
    severity: ERROR
